### ISSUE TITLE
Extension doesn't seems to work

### ISSUE THREAD

**Issue by Aybee5** [ahmafi/gnome-vscode-projects#2]
I installed the extension from the Gnome store, the button is not showing anything when clicked. I am using Ubuntu 22.04

**Comment by ahmafi** [comment]
Hi, actually I wanted to archive this project, because I'm not using it anymore. Have you installed the project manager extension in VSCode?

**Comment by Aybee5** [comment]
I am not aware that I need to install another extension, can you provide the link of the extension so that I can test with the correct one?

**Comment by ahmafi** [comment]
[This extension](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager) should be installed on VSCode, my extension gets it's data from this extension.

**Comment by iramluism** [comment]
> [This extension](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager) should be installed on VSCode, my extension gets it's data from this extension.

its works for me, thanks!
